# Generated by Django 3.0 on 2022-03-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ('datetime_created',), 'verbose_name': 'Url', 'verbose_name_plural': 'Ulr(ы)'},
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='shortened link'),
        ),
    ]
